GET http://localhost:3001/api/notes/1

####
GET http://localhost:3001/api/notes

####

POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "testing after structure set",
    "important": true
}

####

DELETE http://localhost:3001/api/notes/662f53a7fcac839a7b0b6936



####

PUT http://localhost:3001/api/notes/6638692676116026bebeffcf
Content-Type: application/json

{
    "content": "EDITED: testing after structure set",
    "important": false
}