GET http://localhost:3001/api/notes/1

####
GET http://localhost:3001/api/notes

####

# only when login applied..>> Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
POST http://localhost:3001/api/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2ODI0NzVlZDE3YjU3YjAyYWY0ZmU3YSIsImlhdCI6MTcxOTgyMDExNX0.jgUQ7XllLMY1mggkDGty4BNLNJsY3qpOmA2bcqzI6dU


{
    "content": "this is created by user root after auth 60sec after 60sec",
    "important": true
}


####

DELETE http://localhost:3001/api/notes/6682625481c2b7f8de21ed7c



####

PUT http://localhost:3001/api/notes/6638692676116026bebeffcf
Content-Type: application/json

{
    "content": "EDITED2: testing after structure set",
    "important": false
}